import { NextRequest, NextResponse } from 'next/server';
import { writeFileSync, mkdirSync, chmodSync } from 'fs';
import { sanitizeError } from '@/lib/security';
import { requireAdmin } from '@/lib/auth';

function resolvePath(p: string): string {
  if (p.startsWith('~')) return `${process.env.HOME}${p.slice(1)}`;
  return p;
}

export async function POST(request: NextRequest) {
  const denied = requireAdmin(request);
  if (denied) return denied;
  try {
    const { protocol, host, sharePath, mountPoint, smbUser, smbPassword } = await request.json();

    // Validate required fields
    if (!protocol || !host || !sharePath || !mountPoint) {
      return NextResponse.json({ success: false, error: 'Protocol, host, share path, and mount point are required' }, { status: 400 });
    }

    if (!['nfs', 'smb'].includes(protocol)) {
      return NextResponse.json({ success: false, error: 'Protocol must be nfs or smb' }, { status: 400 });
    }

    // Validate no path traversal
    if (mountPoint.includes('..') || sharePath.includes('..')) {
      return NextResponse.json({ success: false, error: 'Path traversal not allowed' }, { status: 400 });
    }

    // Validate host format
    if (!/^[a-zA-Z0-9._-]+$/.test(host)) {
      return NextResponse.json({ success: false, error: 'Invalid host format' }, { status: 400 });
    }

    const resolvedMount = resolvePath(mountPoint);
    // Write to /app/scripts inside the container, which maps to ~/.mmc/scripts on the host
    const containerScriptDir = '/app/scripts';
    const containerScriptPath = `${containerScriptDir}/mount-nas.sh`;
    // The host path shown to the user — use ~ so it works in any user's shell
    const hostScriptPath = '~/.mmc/scripts/mount-nas.sh';

    let installCmd: string;
    let mountSrc: string;
    let mountOpts: string;
    let fstabType: string;
    let credentialSection = '';

    if (protocol === 'nfs') {
      installCmd = 'apt-get install -y -qq nfs-common';
      mountSrc = `${host}:${sharePath}`;
      mountOpts = 'defaults,_netdev,nofail,soft,timeo=30';
      fstabType = 'nfs';
    } else {
      installCmd = 'apt-get install -y -qq cifs-utils';
      mountSrc = `//${host}${sharePath}`;
      fstabType = 'cifs';

      if (smbUser) {
        const credFile = resolvePath('~/.mmc/.nas-credentials');
        const puid = process.env.PUID || '1000';
        const pgid = process.env.PGID || '1000';
        mountOpts = `credentials=${credFile},uid=${puid},gid=${pgid},_netdev,nofail,iocharset=utf8`;
        credentialSection = `
# Store SMB credentials securely
mkdir -p "$(dirname "${credFile}")"
cat > "${credFile}" << 'CRED'
username=${smbUser}
password=${smbPassword || ''}
CRED
chmod 600 "${credFile}"
echo "  Credentials stored at ${credFile} (mode 600)"
`;
      } else {
        const puid = process.env.PUID || '1000';
        const pgid = process.env.PGID || '1000';
        mountOpts = `uid=${puid},gid=${pgid},_netdev,nofail,iocharset=utf8`;
      }
    }

    const fstabLine = `${mountSrc}  ${resolvedMount}  ${fstabType}  ${mountOpts}  0  0`;

    const script = `#!/bin/bash
# ============================================================
# mount-nas.sh — Mount NAS share for Mars Media Centre
# Generated by MMC Migration Tool
# ============================================================
set -e

echo "=== MMC NAS Mount Setup ==="
echo ""

# Install required packages
echo "Installing ${protocol === 'nfs' ? 'nfs-common' : 'cifs-utils and smbclient'}..."
${installCmd}
${protocol === 'smb' ? 'apt-get install -y -qq smbclient 2>/dev/null || true' : ''}
dpkg -l rsync 2>/dev/null | grep -q "^ii" || apt-get install -y -qq rsync
echo "  Done"
${credentialSection}
# Create mount point
mkdir -p "${resolvedMount}"
echo "  Created mount point: ${resolvedMount}"

# Mount the share (unmount first if already mounted)
if mountpoint -q "${resolvedMount}" 2>/dev/null; then
    echo "  ${resolvedMount} is already mounted — unmounting first..."
    umount "${resolvedMount}" || umount -l "${resolvedMount}"
    echo "  Unmounted"
fi
echo "Mounting ${mountSrc} -> ${resolvedMount}..."
mount -t ${fstabType} -o ${mountOpts} "${mountSrc}" "${resolvedMount}"
echo "  Mount successful"

# Verify writable
if touch "${resolvedMount}/.mmc-mount-test" 2>/dev/null; then
    rm -f "${resolvedMount}/.mmc-mount-test"
    echo "  Mount is writable"
else
    echo "  WARNING: Mount appears read-only"
fi

# Add fstab entry (remove existing entry for this mount point first)
if grep -qF "${resolvedMount}" /etc/fstab 2>/dev/null; then
    echo "  Replacing existing fstab entry for ${resolvedMount}"
    sed -i "\\|${resolvedMount}|d" /etc/fstab
fi
echo "${fstabLine}" >> /etc/fstab
echo "  Added fstab entry for persistence"

# Handle WSL auto-mount
if grep -qi microsoft /proc/version 2>/dev/null; then
    echo "  WSL detected — configuring auto-mount"
    if [ -f /etc/wsl.conf ] && grep -q "^\\[boot\\]" /etc/wsl.conf; then
        if grep -q "^command" /etc/wsl.conf; then
            if ! grep -qF "mount -a" /etc/wsl.conf; then
                sed -i "s|^command\\s*=.*|&  \\&\\& mount -a|" /etc/wsl.conf
            fi
        else
            sed -i "/^\\[boot\\]/a command=mount -a" /etc/wsl.conf
        fi
    else
        printf "\\n[boot]\\ncommand=mount -a\\n" >> /etc/wsl.conf
    fi
    echo "  WSL boot config updated"
fi

echo ""
echo "=== NAS mount complete ==="
echo "Free space: $(df -h "${resolvedMount}" | awk 'NR==2 {print \$4}')"
`;

    // Write the script to the shared scripts volume (accessible on host)
    mkdirSync(containerScriptDir, { recursive: true });
    writeFileSync(containerScriptPath, script, { mode: 0o750 });

    return NextResponse.json({
      success: true,
      scriptPath: hostScriptPath,
      command: `sudo bash ${hostScriptPath}`,
      mountPoint: resolvedMount,
      fstabLine,
    });
  } catch (error) {
    return NextResponse.json({ success: false, error: sanitizeError(error) }, { status: 500 });
  }
}
