/**
 * Generation and repair of docker-compose.nas.override.yml — the file that
 * swaps the media bind-mount for a Docker-managed CIFS/NFS volume.
 *
 * WHY media-ui IS NOT IN THIS FILE
 *
 * Docker volume mounts are all-or-nothing at container start: the kernel
 * performs the SMB/NFS mount when the container starts, and if the server
 * doesn't answer, the mount fails and the container refuses to start. There
 * is no "mount if available" option.
 *
 * An earlier version mounted the volume into media-ui too. That made the
 * dashboard unable to boot whenever the NAS blipped — so the one tool you'd
 * use to diagnose "why is my stack down" was itself a casualty of the
 * outage. Circular dependency between the monitoring layer and the thing it
 * monitors.
 *
 * Sonarr/Radarr/Bazarr genuinely need the files and correctly fail without
 * them. media-ui only ever wanted the path for the one-time Migration
 * wizard, and it already reaches host data through the ordinary
 * ${DATA_ROOT} bind-mount in docker-compose.yml, which does not depend on
 * the NAS being up.
 */

export const OVERRIDE_FILENAME = 'docker-compose.nas.override.yml';
export const VOLUME_NAME = 'nas-media';
export const MOUNT_PATH = '/mnt/nas/media';

/** Services that mount the NAS volume. Deliberately excludes media-ui. */
export const NAS_MOUNTED_SERVICES = ['sonarr', 'radarr', 'bazarr'] as const;

export function generateOverrideYaml(protocol: 'smb' | 'nfs'): string {
  const driverOpts = protocol === 'smb'
    ? `      type: cifs
      device: "//\${NAS_HOST}/\${NAS_SHARE}"
      o: "username=\${NAS_USERNAME},password=\${NAS_PASSWORD},uid=\${PUID},gid=\${PGID},file_mode=0644,dir_mode=0755,vers=\${NAS_VERS:-3.0},iocharset=utf8,soft,nounix"`
    : `      type: nfs
      o: "addr=\${NAS_HOST},rw,vers=\${NAS_VERS:-4},soft"
      device: ":\${NAS_SHARE}"`;

  const serviceBlocks = NAS_MOUNTED_SERVICES
    .map((svc) => `  ${svc}:\n    volumes:\n      - ${VOLUME_NAME}:${MOUNT_PATH}`)
    .join('\n');

  return `# ============================================================
# ${OVERRIDE_FILENAME}
# Generated by MMC Migration Tool — do not edit by hand.
#
# Makes Sonarr/Radarr/Bazarr mount the NAS via a Docker-managed named
# volume instead of a host bind-mount.
#
# media-ui is deliberately NOT listed here. A failed CIFS/NFS mount stops
# a container from starting at all, so mounting this into the dashboard
# meant a NAS outage also took away the tool you'd use to diagnose it.
# The dashboard reaches host data via the \${DATA_ROOT} bind-mount instead.
#
# To remove: delete this file and re-run \`docker compose up -d\`.
# ============================================================

volumes:
  ${VOLUME_NAME}:
    driver: local
    driver_opts:
${driverOpts}

services:
${serviceBlocks}
`;
}

/**
 * Strip a `media-ui:` service block that mounts the NAS volume out of an
 * existing override file.
 *
 * Installs created before this was fixed have media-ui in their override on
 * disk; regenerating only happens if the user re-runs the Migration wizard,
 * which they have no reason to do. This lets us repair the file in place.
 *
 * Returns the repaired YAML, or null if no change was needed. Conservative
 * by design: only removes a media-ui block whose body is exactly a volumes
 * list referencing VOLUME_NAME, so a hand-added media-ui block doing
 * something else is left alone.
 */
export function stripMediaUiFromOverride(yaml: string): string | null {
  const lines = yaml.split('\n');
  const out: string[] = [];
  let changed = false;

  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trimEnd() !== '  media-ui:') {
      out.push(lines[i]);
      continue;
    }

    // Collect the block body — every following line indented deeper than
    // the service key (or blank).
    let j = i + 1;
    const body: string[] = [];
    while (j < lines.length) {
      const l = lines[j];
      if (l.trim() === '') { body.push(l); j++; continue; }
      const indent = l.length - l.trimStart().length;
      if (indent <= 2) break;
      body.push(l);
      j++;
    }

    const mountsNasVolume = body.some((l) => l.includes(`${VOLUME_NAME}:${MOUNT_PATH}`));
    const onlyVolumes = body
      .filter((l) => l.trim() !== '')
      .every((l) => /^\s*(volumes:|-\s)/.test(l));

    if (mountsNasVolume && onlyVolumes) {
      // Drop the key and its body. Also drop trailing blank lines the block
      // owned so we don't leave a gap.
      while (out.length > 0 && out[out.length - 1].trim() === '') out.pop();
      i = j - 1;
      changed = true;
    } else {
      out.push(lines[i]);
    }
  }

  if (!changed) return null;
  // Normalise to exactly one trailing newline.
  return out.join('\n').replace(/\n*$/, '\n');
}

/** True if the YAML has a media-ui block mounting the NAS volume. */
export function overrideMountsNasIntoMediaUi(yaml: string): boolean {
  return stripMediaUiFromOverride(yaml) !== null;
}
