import { NextRequest, NextResponse } from 'next/server';
import { writeFileSync, existsSync } from 'fs';
import { sanitizeError } from '@/lib/security';
import { requireAdmin } from '@/lib/auth';
import { logger } from '@/lib/logger';
import { writeEnv } from '@/lib/env';
import { recreateServices, selfRestart } from '@/lib/docker';

const LOG = 'migration';
const PROJECT_DIR = process.env.HOST_PROJECT_DIR || '';
const OVERRIDE_FILENAME = 'docker-compose.nas.override.yml';
const VOLUME_NAME = 'nas-media';
const MOUNT_PATH = '/mnt/nas/media';

interface SetupRequest {
  protocol: 'smb' | 'nfs';
  host: string;
  sharePath: string;
  smbUser?: string;
  smbPassword?: string;
  vers?: string;
}

function generateOverrideYaml(protocol: 'smb' | 'nfs'): string {
  const driverOpts = protocol === 'smb'
    ? `      type: cifs
      device: "//\${NAS_HOST}/\${NAS_SHARE}"
      o: "username=\${NAS_USERNAME},password=\${NAS_PASSWORD},uid=\${PUID},gid=\${PGID},file_mode=0644,dir_mode=0755,vers=\${NAS_VERS:-3.0},iocharset=utf8,soft,nounix"`
    : `      type: nfs
      o: "addr=\${NAS_HOST},rw,vers=4,soft"
      device: ":\${NAS_SHARE}"`;

  return `# ============================================================
# docker-compose.nas.override.yml
# Generated by MMC Migration Tool — do not edit by hand.
# This file makes Sonarr/Radarr/Bazarr/media-ui mount the NAS via
# a Docker-managed named volume instead of a host bind-mount.
# To remove: delete this file and re-run \`docker compose up -d\`.
# ============================================================

volumes:
  ${VOLUME_NAME}:
    driver: local
    driver_opts:
${driverOpts}

services:
  sonarr:
    volumes:
      - ${VOLUME_NAME}:${MOUNT_PATH}
  radarr:
    volumes:
      - ${VOLUME_NAME}:${MOUNT_PATH}
  bazarr:
    volumes:
      - ${VOLUME_NAME}:${MOUNT_PATH}
  media-ui:
    volumes:
      - ${VOLUME_NAME}:${MOUNT_PATH}
`;
}

export async function POST(request: NextRequest) {
  const denied = requireAdmin(request);
  if (denied) return denied;

  if (!PROJECT_DIR) {
    return NextResponse.json({ success: false, error: 'HOST_PROJECT_DIR is not set' }, { status: 500 });
  }

  try {
    const body = (await request.json()) as SetupRequest;
    const { protocol, host, sharePath, smbUser, smbPassword, vers } = body;

    // Validation
    if (!protocol || !host || !sharePath) {
      return NextResponse.json({ success: false, error: 'protocol, host, and sharePath are required' }, { status: 400 });
    }
    if (!['smb', 'nfs'].includes(protocol)) {
      return NextResponse.json({ success: false, error: 'protocol must be smb or nfs' }, { status: 400 });
    }
    if (!/^[a-zA-Z0-9._-]+$/.test(host)) {
      return NextResponse.json({ success: false, error: 'Invalid host format' }, { status: 400 });
    }
    if (sharePath.includes('..') || !/^[a-zA-Z0-9/._ -]+$/.test(sharePath)) {
      return NextResponse.json({ success: false, error: 'Invalid share path' }, { status: 400 });
    }
    if (protocol === 'smb' && !smbUser) {
      return NextResponse.json({ success: false, error: 'SMB requires a username' }, { status: 400 });
    }

    logger.info(LOG, `Setting up NAS volume: ${protocol}://${host}${sharePath}`);

    // Step 1: Write NAS_* values to .env (writeEnv handles backup + atomic write)
    const envUpdates: Record<string, string> = {
      NAS_HOST: host,
      NAS_SHARE: sharePath.replace(/^\/+/, ''),
      NAS_VERS: vers || '3.0',
    };
    if (protocol === 'smb') {
      envUpdates.NAS_USERNAME = smbUser || '';
      envUpdates.NAS_PASSWORD = smbPassword || '';
    }
    writeEnv(envUpdates);
    logger.info(LOG, 'Wrote NAS credentials to .env');

    // Step 2: Generate the override file in the project root
    const overridePath = `${PROJECT_DIR}/${OVERRIDE_FILENAME}`;
    const overrideContent = generateOverrideYaml(protocol);
    writeFileSync(overridePath, overrideContent, { mode: 0o644 });
    logger.info(LOG, `Wrote override file: ${overridePath}`);

    // Step 3: Recreate sonarr, radarr, bazarr — these don't include media-ui,
    // so this call returns cleanly without killing the current request.
    // composeArgs() now picks up the override file automatically because we just wrote it.
    try {
      await recreateServices(['sonarr', 'radarr', 'bazarr']);
      logger.info(LOG, 'Recreated sonarr, radarr, bazarr with the new volume mount');
    } catch (err) {
      const msg = sanitizeError(err);
      logger.error(LOG, `Failed to recreate services: ${msg}`);
      return NextResponse.json({
        success: false,
        error: `Volume configured but service recreation failed: ${msg}. The override file was written; you can recover with: docker compose up -d --force-recreate sonarr radarr bazarr`,
      }, { status: 500 });
    }

    // Step 4: Schedule media-ui recreation via the existing self-restart sidecar.
    // This kills the current container shortly after the response is sent, and
    // a new media-ui container starts with the nas-media volume mounted.
    selfRestart();
    logger.info(LOG, 'Scheduled media-ui self-restart');

    return NextResponse.json({
      success: true,
      overridePath: `${PROJECT_DIR}/${OVERRIDE_FILENAME}`,
      mountPath: MOUNT_PATH,
      message: 'NAS volume configured. Sonarr/Radarr/Bazarr have been recreated. media-ui is restarting now and will reconnect in a few seconds.',
    });
  } catch (error) {
    return NextResponse.json({ success: false, error: sanitizeError(error) }, { status: 500 });
  }
}

// Allow checking whether the override file is currently active
export async function GET(request: NextRequest) {
  const denied = requireAdmin(request);
  if (denied) return denied;

  if (!PROJECT_DIR) {
    return NextResponse.json({ active: false, error: 'HOST_PROJECT_DIR is not set' });
  }

  const overridePath = `${PROJECT_DIR}/${OVERRIDE_FILENAME}`;
  return NextResponse.json({
    active: existsSync(overridePath),
    overridePath,
    mountPath: MOUNT_PATH,
  });
}
